import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import { fileURLToPath } from 'node:url';
// @ts-expect-error — a plain .mjs script with no types, imported for its one
// exported range so the config and the generator cannot disagree about which k
// boards exist.
import { boardKRange } from './scripts/ks-board-pages.mjs';

// Five static pages:
//   index.html         the project site (styles in site/site.css) — root of the build
//   app/index.html     the 3D editor itself, served at /app/
//   levels/index.html  every level of every m x n twist face, at /levels/. An entry
//                      rather than a public/ file so its <link> picks up the same
//                      hashed site.css; its images are in public/levels/img/.
//   twist/index.html   the twist study's front door at /twist/ — the stable link to
//                      hand out, pointing at the write-up, the gallery and the app.
//   mxn/index.html     the MXN Continuation Lab at /mxn/, mirrored from the site it
//                      was built on (see docs/mxn-lab.md). The only React in this
//                      repo, which is why plugin-react is here; it carries its own
//                      stylesheet rather than site.css, and its engine and Python
//                      modules are static files under public/mxn/.
//   mxn/gpu/index.html the compute farm (see docs/mxn-farm.md) — the same engine
//                      driven headlessly over a range of sizes, storing every
//                      answer on Cloudflare so /mxn/ can read them back.
//   mxn/ks/index.html  the k atlas (see docs/mxn-ks.md) — that same shelf read
//                      whole and folded by k, to predict the angle range and the
//                      extension ceiling for sizes nobody has swept yet.
//   mxn/ks/<k>/        the k board (see docs/mxn-ks-board.md) — one page per k,
//                      the whole 8x8 size plane at that k, drawing the judged
//                      ★ best above the engine's run. Thirty real pages rather
//                      than one page with a query string, because /mxn/ks/-1 is
//                      a URL somebody types and this site is static files.
//                      Generated by scripts/ks-board-pages.mjs from the same k
//                      range the inputs below are built from.
//   foldlab/index.html the fold lab (see mocks/foldlab/README.md) — the studio's
//                      own renderer and its own layer panel, over two levels of a
//                      box stitch, printing per layer exactly what it rides over
//                      and ducks under. noindex; it is a working page, not a
//                      published one.
//   mxn/fit/index.html the fitter (see docs/mxn-fit.md) — the same engine asked
//                      for a ring whose neighbouring arms are the same length,
//                      for any m, n, k and hand, and then exported.
//
// Base is set for GitHub Pages project-site hosting (ysetbon.github.io/Scoubidou3D/).
// Override with `vite build --base=/` for root hosting.
const page = (path: string) => fileURLToPath(new URL(path, import.meta.url));

// One input per k board. The range comes from the generator rather than being
// spelt again here, so a k can never have a shell with no input (unpublished) or
// an input with no shell (a build that fails on a missing file).
const boards = Object.fromEntries(
  boardKRange().map((k: number) => [`mxnKs${k < 0 ? `m${-k}` : k}`, page(`mxn/ks/${k}/index.html`)]),
);

const BASE = process.env.BASE_PATH ?? '/Scoubidou3D/';

// Which page `npm run dev` opens. `true` would open the project site root, which
// is the right landing for a visitor and the wrong one for whoever is actually
// working — so it follows the work instead, and the work is /foldlab/. Point it
// somewhere else by setting OPEN, and `OPEN=true` restores the site root:
//
//   $env:OPEN = '/Scoubidou3D/app/'; npm run dev      # the studio
//   $env:OPEN = 'true'; npm run dev                   # the project site
//
// Derived from BASE so a build served from another prefix still opens a real URL.
const OPEN = process.env.OPEN ?? `${BASE}foldlab/`;

export default defineConfig({
  base: BASE,
  plugins: [react({ include: ['**/mxn-lab/**', '**/mxn-farm/**', '**/mxn-ks/**', '**/mxn-fit/**'] })],
  server: { open: OPEN === 'true' ? true : OPEN },
  build: {
    rollupOptions: {
      input: {
        site: page('index.html'),
        app: page('app/index.html'),
        levels: page('levels/index.html'),
        twist: page('twist/index.html'),
        mxn: page('mxn/index.html'),
        mxnFast: page('mxn/fast/index.html'),
        mxnRate: page('mxn/rate/index.html'),
        mxnSemi: page('mxn/semi/index.html'),
        mxnGpu: page('mxn/gpu/index.html'),
        mxnKs: page('mxn/ks/index.html'),
        mxnFit: page('mxn/fit/index.html'),
        foldlab: page('foldlab/index.html'),
        ...boards,
      },
    },
  },
});
