/*
 * Holds the k atlas to what it claims.
 *
 * Four things are checked, and the middle two are the ones that matter.
 *
 * The key parsers, because cache.ts now spells the key grammar in both
 * directions and the two have to be inverses. A parser that quietly disagreed
 * with the builder would show up as a catalogue full of entries the atlas skips
 * and the lab loads, which is a bug you find by noticing an absence.
 *
 * Which band holds which pair count, because it is the opposite of what the
 * lab's sidebar says and nothing else in the repo can tell. m is labelled
 * "H pairs" and the H band searches n of them; worstPairs is max(m,n) and
 * worstCase sums the two, so every existing caller is symmetric under the swap
 * and none of them would notice. The atlas files every number under a band AND
 * a size, so getting it backwards transposes the whole page. Pinned here
 * against a real census.
 *
 * The census derivation, because it is the arithmetic the page and the dump
 * script share, and because three things about a census make it easy to get
 * wrong: the angle axis is ragged, the WINDOW verdicts are an over-sweep rather
 * than results, and BEST is a valid cell.
 *
 * The fit, because a model that cannot recover coefficients it was given is not
 * going to say anything true about a 5x5.
 *
 *   npm run check:atlas
 */
import { existsSync, readFileSync } from "node:fs";
import { resolve } from "node:path";

import {
  parsePicksKey, parseRunKey, parseTraceKey, picksKey, runKey, traceKeyPath,
  type RunDescriptor,
} from "../src/mxn-lab/cache";
import { MAX_PAIR_EXTENSION, worstPairs } from "../src/mxn-lab/search-cost";
import { kLimits } from "../src/mxn-farm/plan";
import {
  bandPairs, bandStatFrom, ceilingSaving, fitPoints, isMeasured, kRelative,
  kRowsFor, recordsFromRun, searchEnvelope, sweptGridStep,
  type AtlasRecord, type FitPoint,
} from "../src/mxn-ks/model";

/**
 * The census numbers, derived independently.
 *
 * Produced by scripts/ks-census-expect.py, which walks the same base64 with
 * numpy and shares no code with src/mxn-ks/model.ts. That is the point: a
 * fixture generated by the module under test would make this check a tautology,
 * and the derivation is exactly the kind of arithmetic that is plausible and
 * wrong (the angle axis is ragged, WINDOW is an over-sweep, BEST is valid).
 */
const EXPECTED_CENSUS = {
  // 2x1's H band is one pair over 21 extensions, and every one of them works at
  // some angle — including 0, which is why its needed ceiling is 0 and why this
  // case is here: a derivation that quietly treated "no extension" as "no
  // solution" would pass on every other cell.
  "2x1 k=1.h": { combos: 21, combosValid: 21, validLo: -181.62, validHi: -138.93, extCeilingNeeded: 0, extPeakValid: 200 },
  // 2x2's V band is the one docs/mxn-lab.md's oracle runs through: 101 of 441
  // combos work, across 19 degrees of a 40 degree window, and the cheapest of
  // them needs 40px where the grid offers 200.
  "2x2 k=1.v": { combos: 441, combosValid: 101, validLo: 102.11, validHi: 121.13, extCeilingNeeded: 40, extPeakValid: 200 },
} as Record<string, {
  combos: number; combosValid: number;
  validLo: number; validHi: number;
  extCeilingNeeded: number; extPeakValid: number;
}>;

let failures = 0;

function check(what: string, got: unknown, want: unknown) {
  const same = JSON.stringify(got) === JSON.stringify(want);
  if (!same) {
    failures += 1;
    console.log(`FAIL  ${what}\n        got  ${JSON.stringify(got)}\n        want ${JSON.stringify(want)}`);
  } else {
    console.log(`ok    ${what}`);
  }
}

const ok = (what: string, condition: boolean) => check(what, condition, true);

function near(what: string, got: number, want: number, tolerance = 1e-6) {
  const close = Number.isFinite(got) && Math.abs(got - want) <= tolerance;
  if (!close) {
    failures += 1;
    console.log(`FAIL  ${what}\n        got  ${got}\n        want ${want} ±${tolerance}`);
  } else {
    console.log(`ok    ${what}`);
  }
}

// ---------------------------------------------------------------------------
console.log("\nkeys — parseRunKey and parseTraceKey invert what builds them");
// ---------------------------------------------------------------------------

const DESCRIPTORS: RunDescriptor[] = [
  { m: 2, n: 2, ks: [1, 2, 2], hand: "lh", direction: "cw", shortArms: true, step: "auto", budget: 400000 },
  { m: 1, n: 4, ks: [-3], hand: "rh", direction: "ccw", shortArms: false, step: 20, budget: 1000 },
  { m: 4, n: 4, ks: [0, -1, 4, 4, 4, 4, 4, 4], hand: "lh", direction: "ccw", shortArms: true, step: 5, budget: 10000000 },
];

DESCRIPTORS.forEach(descriptor => {
  const key = runKey(descriptor);
  const parsed = parseRunKey(key);
  check(`run ${key}`, parsed?.descriptor, descriptor);
  // With and without the catalogue's `run/` prefix: /catalogue lists one way
  // and runKey() builds the other, and both reach this function.
  check(`run/${key}`, parseRunKey(`run/${key}`)?.descriptor, descriptor);

  const traceKey = traceKeyPath(descriptor, 3, "v");
  const trace = parseTraceKey(`trace/${traceKey}`);
  check(`trace ${traceKey}`, trace?.descriptor, descriptor);
  check(`trace ${traceKey} level`, trace?.level, 3);
  check(`trace ${traceKey} band`, trace?.band, "v");

  // The judgements ride the run's own grammar under their own kind, so the
  // pair has to invert the same way run keys do.
  check(`picks/${picksKey(descriptor)}`,
    parsePicksKey(`picks/${picksKey(descriptor)}`)?.descriptor, descriptor);
});

ok("a trace key is not a run key", parseRunKey(`trace/${traceKeyPath(DESCRIPTORS[0], 1, "h")}`) === null);
ok("a run key is not a trace key", parseTraceKey(runKey(DESCRIPTORS[0])) === null);
ok("a picks key is not a run key — a catalogue walk skips them",
  parseRunKey(`picks/${picksKey(DESCRIPTORS[0])}`) === null);
ok("a picks key with a trace tail is refused",
  parsePicksKey(`picks/${traceKeyPath(DESCRIPTORS[0], 1, "h")}`) === null);
ok("a short key is refused", parseRunKey("v3/lh-cw/2x2/1") === null);
ok("a bad hand is refused", parseRunKey("v3/xx-cw/2x2/1/s1-eauto-b400000") === null);
ok("a bad size is refused", parseRunKey("v3/lh-cw/2xx/1/s1-eauto-b400000") === null);
ok("bad flags are refused", parseRunKey("v3/lh-cw/2x2/1/s2-eauto-b400000") === null);
ok("a traversal is refused", parseRunKey("v3/lh-cw/../1/s1-eauto-b400000") === null);
check("the version comes back for the caller to judge",
  parseRunKey("v1/lh-cw/2x2/1/s1-eauto-b400000")?.cacheVersion, "v1");

// ---------------------------------------------------------------------------
console.log("\nk, placed in its own size's band");
// ---------------------------------------------------------------------------

// 2x1 admits -2..3 and 2x2 admits -1..2, so a raw k=2 is the top of one band
// and two thirds up the other. Regressing on the raw value would fit two
// different things to one coefficient.
near("2x1 k=-2 is the bottom of its band", kRelative(2, 1, -2), 0);
near("2x1 k=3 is the top of its band", kRelative(2, 1, 3), 1);
near("2x2 k=2 is the top of its band", kRelative(2, 2, 2), 1);
near("2x1 k=2 is not", kRelative(2, 1, 2), 4 / 5);

// ---------------------------------------------------------------------------
console.log("\nthe grid has a row for every k any size admits");
// ---------------------------------------------------------------------------

// The check the hard-coded [5..-4] would have failed. It was justified from 4x4
// (-3..4) and 1x4 (-4..5), both true, and it missed that kLimits peaks at 3x4:
// twelve cells had no row to be drawn on, and 4x2 k=-5 was on the real shelf.
const SIDES = [1, 2, 3, 4];
const everyCell: { m: number; n: number; k: number }[] = [];
SIDES.forEach(m => SIDES.forEach(n => {
  const { min, max } = kLimits(m, n);
  for (let k = min; k <= max; k += 1) everyCell.push({ m, n, k });
}));

const allRows = kRowsFor(everyCell);
const unreachable = everyCell.filter(cell => !allRows.includes(cell.k));
check("no cell of any size is missing its row", unreachable.map(c => `${c.m}x${c.n} k=${c.k}`), []);
check("the union over sizes 1…4 is -6…7", [Math.min(...allRows), Math.max(...allRows)], [-6, 7]);

// One size on the shelf brings its own whole band with it, so the gaps you
// could still fill are visible rather than hidden.
check("one 3x4 record opens 3x4's whole band",
  kRowsFor([{ m: 3, n: 4, k: 1 }]),
  [7, 6, 5, 4, 3, 2, 1, 0, -1, -2, -3, -4, -5, -6]);
ok("a k on the shelf always gets a row, band or no band",
  kRowsFor([{ m: 1, n: 1, k: 9 }]).includes(9));
check("zero is always drawn", kRowsFor([]).includes(0), true);
ok("an empty shelf still gets a grid", kRowsFor([]).length > 1);
ok("rows run high to low", allRows.every((k, i) => i === 0 || allRows[i - 1] > k));

// ---------------------------------------------------------------------------
console.log("\nthe step the shelf was actually swept at");
// ---------------------------------------------------------------------------

// The other thing the real shelf caught. Its runs are keyed e5-b100000000 --
// an explicit step 5 -- and the panel was calling autoStep(4, 1e8), which
// answers 10. `eauto` and `e5` are different shelves precisely because a
// resolved step is not the same search as an unresolved one.
const swept = sweptGridStep(5, 4, 100_000_000);
check("an explicit step is taken verbatim", swept.step, 5);
ok("…and is not reported as resolved", !swept.resolved);
check("auto still resolves against the budget", sweptGridStep("auto", 4, 100_000_000).step, 10);
ok("…and says that is what it did", sweptGridStep("auto", 4, 100_000_000).resolved);
check("auto at the default budget", sweptGridStep("auto", 3, 400_000).step, 10);

// What the difference was worth: 41 values a pair against 21, to the fourth.
check("step 5 over 4 pairs is 41^4 combos", ceilingSaving(4, 5, 200).now, 41 ** 4);
check("step 10 over 4 pairs is 21^4", ceilingSaving(4, 10, 200).now, 21 ** 4);
ok("which is the 14x the panel was out by",
  Math.abs((41 ** 4) / (21 ** 4) - 14.5) < 0.1);

// ---------------------------------------------------------------------------
console.log("\nrecords — one per level, not one per run");
// ---------------------------------------------------------------------------

const ORACLE = DESCRIPTORS[0];
const records = recordsFromRun("run/v3/x", ORACLE, "2026-08-13T00:00:00Z", {
  m: 2, n: 2, ks: [1, 2, 2], seconds: 27,
  rows: [
    { level: 1, k: 1, expected: 16, gap: [56, 56], ext: [[40, 10], [40, 10]], across: 16, masks: 8, healthy: true },
    { level: 2, k: 2, expected: 16, gap: [57, 57], ext: [[50, 60], [50, 60]], across: 16, masks: 8, healthy: true },
    { level: 3, k: 2, expected: 16, gap: [58, 58], ext: [[60, 50], [60, 50]], across: 16, masks: 8, healthy: true },
  ],
});
check("three levels become three records", records.length, 3);
check("the oracle's extensions survive", records.map(r => r.hExt), [[40, 10], [50, 60], [60, 50]]);
check("extPeak is the worst single pair", records.map(r => r.extPeak), [40, 60, 60]);
check("the same k at two levels stays two records", records.map(r => r.k), [1, 2, 2]);
ok("nothing here is degenerate", records.every(r => !r.degenerate));

const degenerate = recordsFromRun("run/v3/x", ORACLE, "2026-08-13T00:00:00Z", {
  m: 2, n: 2, ks: [0], rows: [
    { level: 1, k: 0, expected: 16, gap: [0, 0], ext: [[], []], across: 16, masks: 8, healthy: true },
  ],
});
ok("k = 0 is degenerate, not missing", degenerate[0].degenerate);

// ---------------------------------------------------------------------------
console.log("\nthe fit recovers what it was given");
// ---------------------------------------------------------------------------

// y = 12 + 9*pairs - 4*|k|, exactly, over sizes that are deliberately not all
// square: where m === n, `m+n` is exactly 2·pairs and the design matrix is
// singular. That is a real property of the model rather than something to avoid
// noticing by only ever testing squares — and the null it produces is checked
// below.
const RECTANGLES = [[1, 1], [2, 1], [2, 2], [3, 1], [3, 2], [3, 3], [4, 2], [4, 4]] as const;
const synthetic: FitPoint[] = [];
RECTANGLES.forEach(([m, n]) => {
  [-1, 1, 2].forEach(k => {
    const pairs = worstPairs(m, n);
    synthetic.push({
      m, n, k, pairs,
      y: 12 + 9 * pairs - 4 * Math.abs(k),
      label: `${m}×${n} k=${k}`,
    });
  });
});
const exact = fitPoints(synthetic);
ok("a clean model fits", !!exact);
near("R² is 1 on noiseless data", exact!.r2, 1, 1e-6);
near("and the residual sd is 0", exact!.sd, 0, 1e-4);
near("it predicts inside the data", exact!.predict(3, 3, 1).value, 12 + 27 - 4, 1e-6);
near("and past it", exact!.predict(6, 6, 1).value, 12 + 54 - 4, 1e-6);
ok("past the data is marked as such", exact!.predict(6, 6, 1).extrapolated);
ok("inside it is not", !exact!.predict(3, 3, 1).extrapolated);
check("how far past is counted", exact!.predict(6, 6, 1).beyond, 2);
ok("too few points is null, not a shrug", fitPoints(synthetic.slice(0, 3)) === null);
// Squares only: m+n is 2·pairs, the design is singular, and there is no unique
// answer. Null rather than whichever one the arithmetic happened to land on.
ok("a shelf of squares alone cannot be fitted",
  fitPoints(synthetic.filter(p => p.m === p.n)) === null);
ok("an interval widens as it leaves the evidence", (() => {
  const noisy = synthetic.map((p, i) => ({ ...p, y: p.y + (i % 3) - 1 }));
  const fit = fitPoints(noisy)!;
  const inside = fit.predict(4, 4, 1);
  const outside = fit.predict(7, 7, 1);
  return (outside.hi - outside.lo) > (inside.hi - inside.lo);
})());

// ---------------------------------------------------------------------------
console.log("\nwhat a lower ceiling would buy");
// ---------------------------------------------------------------------------

// pick_extension_step's own formula: (ext_max / step + 1) ** pairs.
check("3 pairs at step 20, 200px", ceilingSaving(3, 20, 200).now, 11 ** 3);
check("…and at 80px", ceilingSaving(3, 20, 80).proposed, 5 ** 3);
near("which is 10.6x fewer combos", ceilingSaving(3, 20, 80).factor, 11 ** 3 / 5 ** 3, 1e-9);
check("a ceiling above the grid cannot save anything",
  ceilingSaving(2, 20, 999).factor, 1);
check("worstPairs is what the grid is raised to", worstPairs(3, 2), 3);

// ---------------------------------------------------------------------------
console.log("\nthe census, against real engine output");
// ---------------------------------------------------------------------------

const FIXTURE = resolve(process.cwd(), "mocks/fixtures/ks-census.json");
if (!existsSync(FIXTURE)) {
  failures += 1;
  console.log(`FAIL  mocks/fixtures/ks-census.json is missing`
    + `\n        regenerate with: python3 scripts/ks-fixtures.py`);
} else {
  type Side = { plan: Record<string, unknown>; census?: Record<string, unknown> };
  const fixture = JSON.parse(readFileSync(FIXTURE, "utf8")) as
    Record<string, { m: number; n: number; k: number; h: Side; v: Side }>;

  Object.entries(fixture).forEach(([label, entry]) => {
    const { m, n } = entry;
    // THE pin. The lab's sidebar labels m as "H pairs"; the engine gives the H
    // band n of them. Both plans are real trace_plan output.
    check(`${label} · the H band searches n pairs`, entry.h.plan.P, n);
    check(`${label} · the V band searches m pairs`, entry.v.plan.P, m);
    check(`${label} · bandPairs agrees, H`, bandPairs("h", m, n), entry.h.plan.P);
    check(`${label} · bandPairs agrees, V`, bandPairs("v", m, n), entry.v.plan.P);
  });

  // Worked out independently, with numpy over the same census bytes, so this
  // compares two implementations rather than asking one of them to agree with
  // itself. Regenerate with scripts/ks-census-expect.py after an engine change
  // — and if these move without the engine moving, that is the news.
  const EXPECTED: Record<string, {
    combos: number; combosValid: number;
    validLo: number; validHi: number;
    extCeilingNeeded: number; extPeakValid: number;
  }> = EXPECTED_CENSUS;

  Object.entries(fixture).forEach(([label, entry]) => {
    (["h", "v"] as const).forEach(band => {
      const side = entry[band];
      const want = EXPECTED[`${label}.${band}`];
      if (!side.census || !want) return;
      const stat = bandStatFrom(
        band, entry.m, entry.n,
        side.plan as Parameters<typeof bandStatFrom>[3],
        side.census as Parameters<typeof bandStatFrom>[4],
      );
      if (!isMeasured(stat)) {
        failures += 1;
        console.log(`FAIL  ${label}.${band} · expected a measurement, got ${stat.state}`);
        return;
      }
      check(`${label}.${band} · combos`, stat.combos, want.combos);
      check(`${label}.${band} · combos that work`, stat.combosValid, want.combosValid);
      near(`${label}.${band} · valid from`, stat.validLo, want.validLo, 0.01);
      near(`${label}.${band} · valid to`, stat.validHi, want.validHi, 0.01);
      check(`${label}.${band} · needed ceiling`, stat.extCeilingNeeded, want.extCeilingNeeded);
      check(`${label}.${band} · largest valid pair`, stat.extPeakValid, want.extPeakValid);
      ok(`${label}.${band} · the span is the two ends`,
        Math.abs(stat.validSpan - (stat.validHi - stat.validLo)) < 0.02);
      ok(`${label}.${band} · WINDOW cells are excluded from the valid union`,
        stat.inWindowShare > 0 && stat.inWindowShare < 1);
    });
  });

  // A band the engine refused is a real answer and has to survive as one: the
  // page shows "over the trace ceiling" rather than an empty cell inviting the
  // reader to go and compute what has already been decided.
  const refused = bandStatFrom("v", 4, 4,
    { unavailable: true, reason: "194481 combos x 240 angles is over the 4000000 trace ceiling", combos: 194481 },
    { unavailable: true, reason: "over the ceiling" } as never);
  check("a refused census stays unavailable", refused.state, "unavailable");
  check("…and keeps its reason", (refused as { reason: string }).reason.includes("ceiling"), true);
  check("…and is marked as a ceiling", (refused as { overCeiling?: boolean }).overCeiling, true);

  // The other unavailable. Reads completely differently to a reader — there is
  // nothing to census rather than too much — and bridge.py tells them apart by
  // whether it quotes a combo count, which is what the grid's hatch keys on.
  const noSearch = bandStatFrom("h", 1, 1,
    { unavailable: true, reason: "this level solved its horizontal band without a search" },
    { unavailable: true, reason: "this level solved its horizontal band without a search" } as never);
  check("a band with nothing to census is unavailable too", noSearch.state, "unavailable");
  ok("…but is not marked as a ceiling",
    !(noSearch as { overCeiling?: boolean }).overCeiling);
}

// ---------------------------------------------------------------------------
console.log("\nthe search envelope refuses to quote a lower bound");
// ---------------------------------------------------------------------------

// The trap the whole shape exists to prevent. 4x2's V band has four pairs and
// is over the trace ceiling; its H band needs 20px. Reading that as the cell's
// requirement computes to a 2401x saving and capping there would be
// catastrophic, because the band nobody censused could need far more.
const measuredBand = (extCeilingNeeded: number, validSpan: number) => ({
  state: "measured" as const, pairs: 2, combos: 441, combosValid: 101,
  windowLo: 0, windowHi: 40, validLo: 0, validHi: validSpan, validSpan,
  bestLo: 0, bestHi: 1, extCeilingNeeded, extPeakValid: 200,
  perPair: [], counts: [], inWindowShare: 0.34,
});
const overCeiling = {
  state: "unavailable" as const, reason: "194481 combos … over the trace ceiling",
  combos: 194481, overCeiling: true,
};
const noSearch = {
  state: "unavailable" as const, reason: "this level solved its H band without a search",
};

const cellRecord = (m: number, n: number, k: number): AtlasRecord => ({
  runKey: `run/v3/lh-cw/${m}x${n}/${k}/s1-eauto-b400000`,
  m, n, k, level: 1, levels: 1, ks: [k],
  hand: "lh", direction: "cw", shortArms: true, step: "auto", budget: 400000,
  computedAt: "2026-08-13T00:00:00Z", seconds: 1,
  hExt: [40, 10], vExt: [40, 10], extPeak: 40, extTotal: 100,
  gapH: 56, gapV: 56, across: 16, expected: 16, masks: 8,
  healthy: true, degenerate: false,
});

const envelopeCells = [cellRecord(3, 3, 1), cellRecord(4, 2, 1), cellRecord(1, 1, 1)];
const envelope = searchEnvelope({
  generatedAt: "2026-08-13T00:00:00Z", source: "check", cacheVersion: "v3",
  filter: {},
  cells: envelopeCells,
  bandsFor: record => (
    record.m === 4 ? { h: measuredBand(20, 7.2), v: overCeiling }
      : record.m === 1 ? { h: measuredBand(10, 58.9), v: noSearch }
      : { h: measuredBand(60, 9.1), v: measuredBand(50, 8.0) }),
  fits: {},
});

const cellAt = (m: number) => envelope.cells.find(c => c.m === m)!;
check("a fully measured cell is measured", cellAt(3).status, "measured");
check("a cell with a refused band is a lower bound", cellAt(4).status, "lowerBound");
check("…and quotes no combined number at all", cellAt(4).needs.combined, null);
// But what WAS measured is still true. The refused band cannot be reported;
// its partner's own requirement can, and is the more useful half.
ok("…while its measured band keeps its own numbers", !!cellAt(4).needs.h);
check("…and the refused one has none", cellAt(4).needs.v, null);

// A band that solved WITHOUT a search genuinely asks for nothing, so the other
// band's answer stands. Only "too big to census" makes the cell unknowable.
check("a band with nothing to census does not spoil the cell", cellAt(1).status, "measured");
check("the larger band wins", cellAt(3).needs.combined?.extCeiling, 60);
check("and the wider span", cellAt(3).needs.combined?.angleSpan, 9.1);

// Each band over its OWN pair count. H searches n and V searches m, so 4x2's
// two bands differ by 21^2 against 21^4 — the whole reason they are reported
// apart. Getting this from worstPairs would say 194,481 for both.
check("H searches n pairs", cellAt(4).needs.h?.pairs, 2);
check("…so its grid is 21^2", cellAt(4).needs.h?.combosNow, 21 ** 2);
check("3x3's H band is 3 pairs", cellAt(3).needs.h?.pairs, 3);
check("its V band is 3 too", cellAt(3).needs.v?.pairs, 3);
// The bands disagree, which is the point of splitting them: 60px against 50px.
check("each band keeps its own ceiling",
  [cellAt(3).needs.h?.extCeiling, cellAt(3).needs.v?.extCeiling], [60, 50]);
check("and its own angle range",
  [cellAt(3).needs.h?.angleSpan, cellAt(3).needs.v?.angleSpan], [9.1, 8]);
ok("with the ends of that range, not just its width",
  cellAt(3).needs.h?.angleTo === 9.1 && cellAt(3).needs.h?.angleFrom === 0);

// The saving is ceilingSaving's own arithmetic over the step actually swept:
// 3 pairs at step 10 is 21^3 against a 60px ceiling's 7^3.
check("3x3's combos now", cellAt(3).needs.combined?.combosNow, 21 ** 3);
check("…and at its own ceiling", cellAt(3).needs.combined?.combosAtCeiling, 7 ** 3);
check("totals count only the measured", envelope.totals.cellsMeasured, 2);
check("…and sum their combos", envelope.totals.combosNow, 21 ** 3 + 21);
ok("every measured cell carries a combined need",
  envelope.cells.filter(c => c.status === "measured").every(c => c.needs.combined));
ok("no lower bound carries one",
  envelope.cells.filter(c => c.status === "lowerBound").every(c => c.needs.combined === null));
ok("the file argues its own limits", envelope.caveats.length >= 4);
ok("…including that the ceiling is not settable",
  envelope.caveats.some(c => c.includes("NOT settable per run")));
check("and states what it measured against",
  envelope.engine.maxPairExtension, MAX_PAIR_EXTENSION);

// ---------------------------------------------------------------------------
console.log("\nthe committed snapshot, against the oracle");
// ---------------------------------------------------------------------------

// public/mxn/ks-atlas.json is what the mock and /mxn/ks/?data=mock read, and it
// is regenerated by hand from a Worker or from the engine. docs/mxn-lab.md pins
// 2x2 ks=[1,2,2] to extensions (40,10), (50,60), (60,50) with every level 16
// across and 8 masks, and qa:cache asserts exactly that through the whole
// stack. Asserting it here too costs nothing and means a snapshot regenerated
// against a broken engine, a wrong hand, or a half-finished sweep cannot be
// committed quietly.
const SNAPSHOT = resolve(process.cwd(), "public/mxn/ks-atlas.json");
if (!existsSync(SNAPSHOT)) {
  failures += 1;
  console.log("FAIL  public/mxn/ks-atlas.json is missing"
    + "\n        regenerate with: npm run dump:ks -- --url <worker>");
} else {
  const dump = JSON.parse(readFileSync(SNAPSHOT, "utf8")) as {
    records: { m: number; n: number; ks: number[]; level: number; k: number;
               hExt: number[]; vExt: number[]; extPeak: number;
               across: number; expected: number; masks: number; healthy: boolean }[];
  };
  const oracle = dump.records
    .filter(r => r.ks.join(" ") === "1 2 2")
    .sort((a, b) => a.level - b.level);
  check("the oracle sequence is on the snapshot", oracle.length, 3);
  if (oracle.length === 3) {
    check("its extensions are (40,10), (50,60), (60,50)",
      oracle.map(r => r.hExt), [[40, 10], [50, 60], [60, 50]]);
    check("H and V agree on it", oracle.map(r => r.vExt), oracle.map(r => r.hExt));
    check("its ks are 1, 2, 2", oracle.map(r => r.k), [1, 2, 2]);
    ok("every level is 16 across of 16",
      oracle.every(r => r.across === 16 && r.expected === 16));
    ok("every level is 8 masks and a weave",
      oracle.every(r => r.masks === 8 && r.healthy));
  }
  ok("the snapshot carries more than one level, so the level filter has work to do",
    new Set(dump.records.map(r => r.level)).size > 1);
  // The finding the whole page is built around. If a future engine stops doing
  // this, the page's argument changes and someone should have to notice.
  const big = dump.records.find(r => r.m === 4 && r.n === 4 && r.k === 1 && r.level === 1);
  if (big) {
    check("4x4 k=1 still picks the top of the grid", big.extPeak, MAX_PAIR_EXTENSION);
  } else {
    console.log("note  4x4 k=1 is not on this snapshot — the ceiling finding is unchecked");
  }
}

// ---------------------------------------------------------------------------
console.log(failures ? `\n${failures} failed\n` : "\nall good\n");
process.exit(failures ? 1 : 0);
