// Mock harness for the lab's two busy states. Dev only: mocks/widgets.html is
// not a build input, so nothing here ships.
//
// It mounts the REAL components — TraceSweep and LiveCandidateFigure — against
// payloads the REAL engine produced (mocks/fixtures/*.json, regenerated by
// scripts/mock-fixtures.py). The only thing standing in is the worker: the
// census progress and the candidate stream are driven from here on a timer,
// because Pyodide cannot be reached from every environment this is looked at
// in. Everything the widgets draw from — the band's extension grid, its angle
// window, its gap bounds, the rings on the tiles — is engine output.
import { useEffect, useMemo, useRef, useState } from "react";
import { createRoot } from "react-dom/client";

import type { Strand } from "./exact-draw";
import { TraceSweep, type TracePlan, type TraceProgress } from "./trace-panel";
import {
  LiveCandidateFigure, autoStep, comboCount, createFrameStore, worstCase,
  worstPairs, type ProgressFrame,
} from "./weave-studio";
import "./lab.css";

type Ring = {
  ext: number[]; angle: number; strands: Strand[];
  across: number; expected: number; healthy: boolean;
};

// Resolved against the page, not this module: the module is served out of
// /src/ while the fixtures sit beside the HTML that mounts it. A page that
// inlined them says so on the window instead — see scripts/build-mock.mjs,
// which folds this whole harness into one file that opens from anywhere.
declare global {
  interface Window { __MOCK_FIXTURES?: Record<string, unknown>; }
}
const load = async <T,>(name: string): Promise<T> => {
  const inlined = window.__MOCK_FIXTURES?.[name];
  if (inlined) return inlined as T;
  return (await fetch(new URL(`fixtures/${name}`, window.location.href))).json();
};

/** A · the level widget while its band is being censused. */
function SweepPanel({ plans, rings }: {
  plans: Record<"h" | "v", TracePlan>;
  rings: Ring[];
}) {
  const [band, setBand] = useState<"h" | "v">("v");
  const [planned, setPlanned] = useState(true);
  const [running, setRunning] = useState(true);
  const [done, setDone] = useState(0);
  const [replay] = useState(createFrameStore);
  const plan = plans[band];

  // Stands in for the replay's own candidate relay, which is what the widget
  // draws before any plan exists. Real rings, tagged with the band traced.
  const at = useRef(0);
  useEffect(() => {
    if (planned) return undefined;
    const id = window.setInterval(() => {
      const i = at.current;
      const ring = rings[i % rings.length];
      replay.set({
        id: 1, level: 1, k: 1,
        phase: `${band === "h" ? "horizontal" : "vertical"} candidate`,
        trace: band === "h" ? "horizontal" : "vertical",
        completed: Math.min(plan.combos, (i + 1) * 17), total: plan.combos,
        valid: Math.floor(i / 4), angle: ring.angle, extensions: ring.ext,
        strands: ring.strands,
      });
      at.current = i + 1;
    }, 140);
    return () => window.clearInterval(id);
  }, [planned, band, plan, rings, replay]);

  // Stands in for the worker's own emitTrace: the census walks its combos at a
  // steady rate and says so a couple of hundred times on the way.
  useEffect(() => {
    if (!running || !planned) return undefined;
    const id = window.setInterval(() => {
      setDone(current => (current >= plan.combos ? 0 : Math.min(
        plan.combos, current + Math.max(1, Math.round(plan.combos / 90)))));
    }, 220);
    return () => window.clearInterval(id);
  }, [running, planned, plan]);

  useEffect(() => { setDone(0); }, [band, planned]);

  const progress: TraceProgress | undefined = planned && (running || done > 0)
    ? { level: 1, band, combosDone: done, combos: plan.combos,
        nAngles: plan.nAngles }
    : undefined;

  return (
    <section className="mock-case">
      <header>
        <h2>A · level widget, band being censused</h2>
        <div className="mock-controls">
          <span className="mock-switch" role="group" aria-label="Band">
            {(["h", "v"] as const).map(side => (
              <button key={side} type="button" aria-pressed={band === side}
                onClick={() => setBand(side)}>{side.toUpperCase()}</button>
            ))}
          </span>
          <span className="mock-switch" role="group" aria-label="Stage">
            <button type="button" aria-pressed={!planned}
              onClick={() => setPlanned(false)}>replaying</button>
            <button type="button" aria-pressed={planned}
              onClick={() => setPlanned(true)}>sweeping</button>
          </span>
          <button type="button" className="mock-toggle" aria-pressed={running}
            onClick={() => setRunning(value => !value)}>
            {running ? "pause census" : "resume census"}
          </button>
        </div>
      </header>
      <div className="mock-frame">
        <div className="level-widget is-open">
          <div className="level-widget-body">
            <div className="trace-pending">
              <TraceSweep band={band} level={1}
                plan={planned ? plan : undefined} progress={progress}
                replay={replay} stage={{ level: 1, k: 1, label: "L1",
                  strands: rings[0].strands }} />
              <p>{planned
                ? `Sweeping all ${plan.combos.toLocaleString()} extension combos of `
                  + `L1's ${band === "h" ? "horizontal" : "vertical"} band against `
                  + `${plan.nAngles} angles each — ${plan.evaluations.toLocaleString()} `
                  + "tests, none skipped."
                : "Replaying L1 and sweeping every combo of its "
                  + `${band === "h" ? "horizontal" : "vertical"} band against every angle…`}</p>
              <div className="trace-pending-actions">
                {(["h", "v"] as const).map(side => (
                  <button key={side} type="button" aria-pressed={band === side}
                    onClick={() => setBand(side)}>{side.toUpperCase()}</button>
                ))}
              </div>
            </div>
          </div>
        </div>
      </div>
      <dl className="mock-facts">
        <div><dt>pairs</dt><dd>{plan.P}</dd></div>
        <div><dt>extensions</dt><dd>{plan.vals.length} × {plan.step}° grid</dd></div>
        <div><dt>combos</dt><dd>{plan.combos.toLocaleString()}</dd></div>
        <div><dt>angles / combo</dt><dd>{plan.nAngles} ({plan.insideCount} in window)</dd></div>
        <div><dt>tests</dt><dd>{plan.evaluations.toLocaleString()}</dd></div>
        <div><dt>gap bounds</dt><dd>{plan.minGap.toFixed(0)}–{plan.maxGap.toFixed(0)} px</dd></div>
      </dl>
    </section>
  );
}

/** B · the run's busy state, with the plaque carrying the run's scale. */
function CandidatePanel({ rings }: { rings: Ring[] }) {
  const [m, setM] = useState(2);
  const [n, setN] = useState(2);
  const [levels, setLevels] = useState(3);
  const [running, setRunning] = useState(true);
  const [store] = useState(createFrameStore);
  const cursor = useRef(0);

  const step = autoStep(worstPairs(m, n), 400_000);
  const worst = useMemo(() => worstCase(m, n, levels, step), [m, n, levels, step]);
  const totals = useMemo(
    () => [comboCount(step, m), comboCount(step, n)], [step, m, n]);

  // Stands in for the engine's own frame relay: groups in the order the run
  // walks them, each filling its own grid, with a real ring on every tile.
  useEffect(() => {
    if (!running) return undefined;
    const id = window.setInterval(() => {
      const groups = levels * 2;
      const per = 46;                       // frames spent on one group
      const at = cursor.current;
      const group = Math.floor(at / per) % groups;
      const within = (at % per) / per;
      const total = totals[group % 2];
      const ring = rings[at % rings.length];
      const frame: ProgressFrame = {
        id: 1,
        level: Math.floor(group / 2) + 1,
        k: 1,
        phase: `${group % 2 === 0 ? "horizontal" : "vertical"} candidate`,
        completed: Math.round(total * within),
        total,
        valid: Math.floor(within * 9),
        angle: ring.angle,
        extensions: ring.ext,
        strands: ring.strands,
      };
      store.set(frame);
      cursor.current = at + 1;
    }, 90);
    return () => window.clearInterval(id);
  }, [running, levels, totals, rings, store]);

  return (
    <section className="mock-case">
      <header>
        <h2>B · run in progress, candidates arriving</h2>
        <div className="mock-controls">
          <label>m <input type="number" min={1} max={4} value={m}
            onChange={e => setM(Math.max(1, Math.min(4, Number(e.target.value))))} /></label>
          <label>n <input type="number" min={1} max={4} value={n}
            onChange={e => setN(Math.max(1, Math.min(4, Number(e.target.value))))} /></label>
          <label>levels <input type="number" min={1} max={8} value={levels}
            onChange={e => setLevels(Math.max(1, Math.min(8, Number(e.target.value))))} /></label>
          <button type="button" className="mock-toggle" aria-pressed={running}
            onClick={() => setRunning(value => !value)}>
            {running ? "pause search" : "resume search"}
          </button>
        </div>
      </header>
      <div className="mock-frame is-results">
        <LiveCandidateFigure store={store} worst={worst} />
      </div>
      <dl className="mock-facts">
        <div><dt>step</dt><dd>auto ({step})</dd></div>
        <div><dt>H group</dt><dd>{totals[0].toLocaleString()} combos</dd></div>
        <div><dt>V group</dt><dd>{totals[1].toLocaleString()} combos</dd></div>
        <div><dt>groups</dt><dd>{worst.groups}</dd></div>
        <div><dt>worst case</dt><dd>{worst.total.toLocaleString()} combos</dd></div>
      </dl>
    </section>
  );
}

function Mock() {
  const [plans, setPlans] = useState<Record<"h" | "v", TracePlan> | null>(null);
  const [rings, setRings] = useState<Ring[] | null>(null);
  const [failed, setFailed] = useState<string | null>(null);

  useEffect(() => {
    Promise.all([
      load<Record<"h" | "v", TracePlan>>("trace-plan-l1.json"),
      load<Ring[]>("candidates-l1.json"),
    ]).then(([p, r]) => { setPlans(p); setRings(r); })
      .catch(error => setFailed(String(error)));
  }, []);

  return (
    <main className="mock-shell">
      <header className="mock-masthead">
        <b>Mock</b>
        <span>lab busy states · real engine payloads, stand-in worker</span>
        <a href="../mxn/">the lab itself →</a>
      </header>
      {failed && <p className="mock-error">
        Could not read mocks/fixtures — run <code>python3 scripts/mock-fixtures.py</code>. ({failed})
      </p>}
      {plans && rings && <SweepPanel plans={plans} rings={rings} />}
      {rings && <CandidatePanel rings={rings} />}
    </main>
  );
}

const root = document.getElementById("mock");
if (!root) throw new Error("#mock is missing from mocks/widgets.html");
createRoot(root).render(<Mock />);
